from experta import Fact

# Define the BookFact class for both knowledge base and inference
class BookFact(Fact):
    """Represents a book and acts as a fact for the expert system."""
    title = str
    category = str
    author = str
    keywords = set  # Use set for easier keyword operations
    rating = float
    target_audience = str
    language = str
    book_type = str

    def __str__(self):
        return (f"Title: {self.title}, Author: {self.author}, Category: {self.category}, "
                f"Rating: {self.rating}, Target Audience: {self.target_audience}, "
                f"Language: {self.language}, Type: {self.book_type}")

knowledge_base = [
    BookFact(title="The Great Adventure", category="Fiction", author="John Doe",
             keywords={"adventure", "mystery"}, rating=4.5, target_audience="Adults",
             language="English", book_type="Paperback"),
    BookFact(title="Learning Python", category="Technology", author="Mark Smith",
             keywords={"programming", "python", "coding"}, rating=4.7,
             target_audience="Beginners", language="English", book_type="Hardcover"),
    BookFact(title="AI for Everyone", category="Technology", author="Andrew Ng",
             keywords={"ANN", "nlp", "machine learning"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Joy of Cooking", category="Cooking", author="Julia Child",
             keywords={"cooking", "recipes", "food"}, rating=4.6, target_audience="Adults",
             language="English", book_type="Hardcover"),
    BookFact(title="The Silent World of Nicholas Quinn", category="Mystery", author="Colin Dexter",
             keywords={"mystery", "detective", "suspense"}, rating=4.2,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Psychology of Learning", category="Psychology", author="Sigmund Freud",
             keywords={"psychology", "learning", "behavior"}, rating=4.4,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Hobbit", category="Fantasy", author="J.R.R. Tolkien",
             keywords={"fantasy", "adventure", "dragons"}, rating=4.9, target_audience="Teens",
             language="English", book_type="Hardcover"),
    BookFact(title="JavaScript Essentials", category="Technology", author="David Flanagan",
             keywords={"programming", "javascript", "web development"}, rating=4.3,
             target_audience="Intermediate", language="English", book_type="Paperback"),
    BookFact(title="Cooking with Love", category="Cooking", author="Rachel Ray",
             keywords={"cooking", "easy recipes", "family meals"}, rating=4.5,
             target_audience="Family", language="English", book_type="Paperback"),
    BookFact(title="Deep Learning", category="Technology", author="Ian Goodfellow",
             keywords={"AI", "deep learning", "neural networks"}, rating=4.9,
             target_audience="Advanced", language="English", book_type="Hardcover"),
    BookFact(title="Principles of Quantum Mechanics", category="Science", author="David Griffiths",
             keywords={"quantum", "physics", "mechanics"}, rating=4.8,
             target_audience="Advanced", language="English", book_type="Hardcover"),
    BookFact(title="Meditations", category="Philosophy", author="Marcus Aurelius",
             keywords={"stoicism", "philosophy", "life lessons"}, rating=4.6,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="Crime and Punishment", category="Fiction", author="Fyodor Dostoevsky",
             keywords={"crime", "morality", "psychology"}, rating=4.9,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="A Brief History of Time", category="Science", author="Stephen Hawking",
             keywords={"cosmology", "universe", "science"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Art of War", category="Philosophy", author="Sun Tzu",
             keywords={"strategy", "war", "leadership"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="To Kill a Mockingbird", category="Fiction", author="Harper Lee",
             keywords={"racism", "justice", "coming of age"}, rating=4.9,
             target_audience="Teens", language="English", book_type="Paperback"),
    BookFact(title="The Catcher in the Rye", category="Fiction", author="J.D. Salinger",
             keywords={"rebellion", "identity", "adolescence"}, rating=4.4,
             target_audience="Teens", language="English", book_type="Hardcover"),
    BookFact(title="Machine Learning Yearning", category="Technology", author="Andrew Ng",
             keywords={"machine learning", "AI", "nlp"}, rating=4.7,
             target_audience="Intermediate", language="English", book_type="Paperback"),
    BookFact(title="Sapiens: A Brief History of Humankind", category="History", author="Yuval Noah Harari",
             keywords={"history", "human evolution", "society"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="Clean Code", category="Technology", author="Robert C. Martin",
             keywords={"programming", "software engineering", "best practices"}, rating=4.7,
             target_audience="Developers", language="English", book_type="Paperback"),
    BookFact(title="The Pragmatic Programmer", category="Technology", author="Andy Hunt",
             keywords={"programming", "software development", "coding"}, rating=4.8,
             target_audience="Intermediate", language="English", book_type="Paperback"),
    BookFact(title="The Lean Startup", category="Business", author="Eric Ries",
             keywords={"business", "startup", "entrepreneurship"}, rating=4.6,
             target_audience="Entrepreneurs", language="English", book_type="Paperback"),
    BookFact(title="Becoming", category="Biography", author="Michelle Obama",
             keywords={"autobiography", "inspiration", "success"}, rating=4.9,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="The Alchemist", category="Fiction", author="Paulo Coelho",
             keywords={"self-discovery", "dreams", "journey"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="Atomic Habits", category="Self-help", author="James Clear",
             keywords={"habits", "productivity", "self-improvement"}, rating=4.8,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Power of Now", category="Self-help", author="Eckhart Tolle",
             keywords={"mindfulness", "spirituality", "present"}, rating=4.6,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Dune", category="Science Fiction", author="Frank Herbert",
             keywords={"sci-fi", "adventure", "space"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="The Shining", category="Horror", author="Stephen King",
             keywords={"horror", "thriller", "paranormal"}, rating=4.7,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="Pride and Prejudice", category="Fiction", author="Jane Austen",
             keywords={"romance", "society", "drama"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="1984", category="Fiction", author="George Orwell",
             keywords={"dystopia", "politics", "freedom"}, rating=4.9,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="The Road", category="Fiction", author="Cormac McCarthy",
             keywords={"post-apocalypse", "journey", "survival"}, rating=4.5,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Name of the Wind", category="Fantasy", author="Patrick Rothfuss",
             keywords={"magic", "adventure", "hero's journey"}, rating=4.8,
             target_audience="Teens", language="English", book_type="Hardcover"),
    BookFact(title="The Intelligent Investor", category="Finance", author="Benjamin Graham",
             keywords={"investment", "finance", "stock market"}, rating=4.7,
             target_audience="Investors", language="English", book_type="Paperback"),
    BookFact(title="Design Patterns", category="Technology", author="Erich Gamma",
             keywords={"programming", "design", "patterns"}, rating=4.9,
             target_audience="Advanced", language="English", book_type="Hardcover"),
    BookFact(title="The Lord of the Rings", category="Fantasy", author="J.R.R. Tolkien",
             keywords={"fantasy", "adventure", "epic"}, rating=4.9,
             target_audience="Adults", language="English", book_type="Hardcover"),
    BookFact(title="The Kite Runner", category="Fiction", author="Khaled Hosseini",
             keywords={"family", "friendship", "redemption"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Theory of Everything", category="Science", author="Stephen Hawking",
             keywords={"cosmology", "science", "physics"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Think and Grow Rich", category="Self-help", author="Napoleon Hill",
             keywords={"success", "wealth", "personal development"}, rating=4.6,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Subtle Art of Not Giving a F*ck", category="Self-help", author="Mark Manson",
             keywords={"mindset", "philosophy", "self-improvement"}, rating=4.5,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Art of Computer Programming", category="Technology", author="Donald Knuth",
             keywords={"algorithms", "computer science", "programming"}, rating=4.9,
             target_audience="Advanced", language="English", book_type="Hardcover"),
    BookFact(title="Good to Great", category="Business", author="Jim Collins",
             keywords={"leadership", "business", "strategy"}, rating=4.7,
             target_audience="Entrepreneurs", language="English", book_type="Paperback"),
    BookFact(title="Inferno", category="Fiction", author="Dan Brown",
             keywords={"thriller", "mystery", "adventure"}, rating=4.6,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="Man's Search for Meaning", category="Philosophy", author="Viktor Frankl",
             keywords={"psychology", "purpose", "philosophy"}, rating=4.8,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Zero to One", category="Business", author="Peter Thiel",
             keywords={"startups", "entrepreneurship", "innovation"}, rating=4.6,
             target_audience="Entrepreneurs", language="English", book_type="Paperback"),
    BookFact(title="Rich Dad Poor Dad", category="Finance", author="Robert Kiyosaki",
             keywords={"wealth", "investment", "money"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Educated", category="Biography", author="Tara Westover",
             keywords={"autobiography", "education", "resilience"}, rating=4.8,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="The Four Agreements", category="Self-help", author="Don Miguel Ruiz",
             keywords={"mindfulness", "spirituality", "wisdom"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Brave New World", category="Fiction", author="Aldous Huxley",
             keywords={"dystopia", "society", "science fiction"}, rating=4.6,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Innovator's Dilemma", category="Business", author="Clayton M. Christensen",
             keywords={"innovation", "business", "disruption"}, rating=4.7,
             target_audience="Entrepreneurs", language="English", book_type="Hardcover"),
    BookFact(title="Algorithms to Live By", category="Technology", author="Brian Christian",
             keywords={"algorithms", "decision-making", "computer science"}, rating=4.5,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The War of Art", category="Self-help", author="Steven Pressfield",
             keywords={"creativity", "discipline", "motivation"}, rating=4.6,
             target_audience="Artists", language="English", book_type="Paperback"),
    BookFact(title="The Big Short", category="Finance", author="Michael Lewis",
             keywords={"finance", "economics", "stock market"}, rating=4.8,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="The Outsiders", category="Fiction", author="S.E. Hinton",
             keywords={"friendship", "coming of age", "drama"}, rating=4.6,
             target_audience="Teens", language="English", book_type="Paperback"),
    BookFact(title="Harry Potter and the Sorcerer's Stone", category="Fantasy", author="J.K. Rowling",
             keywords={"magic", "adventure", "fantasy"}, rating=4.9,
             target_audience="Teens", language="English", book_type="Hardcover"),
    BookFact(title="Born a Crime", category="Biography", author="Trevor Noah",
             keywords={"autobiography", "humor", "resilience"}, rating=4.8,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="Outliers", category="Self-help", author="Malcolm Gladwell",
             keywords={"success", "statistics", "psychology"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Handmaid's Tale", category="Fiction", author="Margaret Atwood",
             keywords={"dystopia", "society", "feminism"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="Sapiens: A Brief History of Humankind", category="History", author="Yuval Noah Harari",
             keywords={"history", "evolution", "humanity"}, rating=4.8,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="Atomic Habits", category="Self-help", author="James Clear",
             keywords={"habits", "self-improvement", "productivity"}, rating=4.9,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Dune", category="Science Fiction", author="Frank Herbert",
             keywords={"science fiction", "epic", "adventure"}, rating=4.7,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Catcher in the Rye", category="Fiction", author="J.D. Salinger",
             keywords={"coming of age", "classic", "drama"}, rating=4.3,
             target_audience="Teens", language="English", book_type="Paperback"),
    BookFact(title="Grit: The Power of Passion and Perseverance", category="Psychology", author="Angela Duckworth",
             keywords={"perseverance", "motivation", "success"}, rating=4.6,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Lean Startup", category="Business", author="Eric Ries",
             keywords={"entrepreneurship", "business", "startups"}, rating=4.7,
             target_audience="Entrepreneurs", language="English", book_type="Paperback"),
    BookFact(title="A Brief History of Time", category="Science", author="Stephen Hawking",
             keywords={"cosmology", "universe", "physics"}, rating=4.8,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="The Alchemist", category="Fiction", author="Paulo Coelho",
             keywords={"philosophy", "journey", "dreams"}, rating=4.8,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="To Kill a Mockingbird", category="Fiction", author="Harper Lee",
             keywords={"justice", "race", "classic"}, rating=4.9,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Road", category="Fiction", author="Cormac McCarthy",
             keywords={"post-apocalypse", "journey", "survival"}, rating=4.4,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The 5 Love Languages", category="Relationships", author="Gary Chapman",
             keywords={"love", "communication", "relationships"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Thinking, Fast and Slow", category="Psychology", author="Daniel Kahneman",
             keywords={"psychology", "decision-making", "cognition"}, rating=4.7,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="1984", category="Fiction", author="George Orwell",
             keywords={"dystopia", "politics", "freedom"}, rating=4.8,
             target_audience="Adults", language="English", book_type="Paperback"),
    BookFact(title="The Power of Now", category="Self-help", author="Eckhart Tolle",
             keywords={"mindfulness", "spirituality", "presence"}, rating=4.6,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Pragmatic Programmer", category="Technology", author="Andrew Hunt",
             keywords={"programming", "software development", "best practices"}, rating=4.8,
             target_audience="Intermediate", language="English", book_type="Paperback"),
    BookFact(title="Pride and Prejudice", category="Fiction", author="Jane Austen",
             keywords={"romance", "society", "classic"}, rating=4.9,
             target_audience="General", language="English", book_type="Hardcover"),
    BookFact(title="Meditations", category="Philosophy", author="Marcus Aurelius",
             keywords={"stoicism", "wisdom", "self-reflection"}, rating=4.7,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="Clean Code", category="Technology", author="Robert C. Martin",
             keywords={"programming", "best practices", "software engineering"}, rating=4.8,
             target_audience="Advanced", language="English", book_type="Paperback"),
    BookFact(title="How to Win Friends and Influence People", category="Self-help", author="Dale Carnegie",
             keywords={"communication", "success", "leadership"}, rating=4.8,
             target_audience="General", language="English", book_type="Paperback"),
    BookFact(title="The Fellowship of the Ring", category="Fantasy", author="J.R.R. Tolkien",
             keywords={"fantasy", "adventure", "epic"}, rating=4.9,
             target_audience="Teens", language="English", book_type="Hardcover"),
    
    BookFact(title="The Hundred-Page Machine Learning Book", category="Data Science", author="Andriy Burkov",
         keywords={"machine learning", "artificial intelligence", "data science", "nlp"}, rating=4.7,
         target_audience="Students and professionals", language="English", book_type="Paperback"),

BookFact(title="Deep Learning", category="Data Science", author="Ian Goodfellow", 
         keywords={"deep learning", "neural networks", "AI", "machine learning"}, rating=4.9, 
         target_audience="Researchers and students", language="English", book_type="Hardcover"),

BookFact(title="Data Science for Business", category="Data Science", author="Foster Provost & Tom Fawcett",
         keywords={"data science", "business", "analytics", "predictive modeling"}, rating=4.6,
         target_audience="Business professionals", language="English", book_type="Paperback"),

BookFact(title="Python Machine Learning", category="Data Science", author="Sebastian Raschka", 
         keywords={"machine learning", "nlp", "data science", "deep learning"}, rating=4.8,
         target_audience="Developers and students", language="English", book_type="Paperback"),

BookFact(title="Artificial Intelligence: A Modern Approach", category="AI", author="Stuart Russell & Peter Norvig",
         keywords={"AI", "artificial intelligence", "algorithms", "intelligence"}, rating=4.8, 
         target_audience="Students and professionals", language="English", book_type="Hardcover"),

BookFact(title="Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", category="Data Science", 
         author="Aurélien Géron", keywords={"machine learning", "TensorFlow", "Scikit-Learn", "AI"}, rating=4.7, 
         target_audience="Developers and students", language="English", book_type="Paperback"),

BookFact(title="Machine Learning Yearning", category="AI", author="Andrew Ng", 
         keywords={"machine learning", "AI", "deep learning", "nlp"}, rating=4.9, 
         target_audience="Students and professionals", language="English", book_type="eBook"),

BookFact(title="The Data Science Handbook", category="Data Science", author="Carl Shan, William Chen, Henry Wang, and Max Song",
         keywords={"data science", "interviews", "machine learning", "career"}, rating=4.6, 
         target_audience="Students and professionals", language="English", book_type="Paperback"),

BookFact(title="The Elements of Statistical Learning", category="Data Science", author="Trevor Hastie, Robert Tibshirani, Jerome Friedman",
         keywords={"statistical learning", "machine learning", "algorithms", "AI"}, rating=4.8, 
         target_audience="Researchers and students", language="English", book_type="Hardcover"),

BookFact(title="Introduction to Machine Learning with Python", category="Data Science", author="Andreas C. Müller & Sarah Guido",
         keywords={"machine learning", "Python", "data science", "nlp"}, rating=4.7, 
         target_audience="Developers and students", language="English", book_type="Paperback"),

]

    


